### ISSUE TITLE
Some confusion about Figure 1 in the paper

### ISSUE THREAD

**Issue by zyfone** [K2OKOH/MAD#1]
Hello,bro
First of all, thank you for the open source code, but I still have some questions about the paper

More feature extraction to prove the presence of non-causal factors in domain invariant features, in Fig1.

**Could it be that the initial feature extraction capability of the discriminator is inherently weak, thus affecting the loss?** 
In other words, it is not that the domain-invariant features contain non-causal factors, but that a more powerful discriminator can provide more significantly intrinsic discrepancy of the domain.
If a more complex discriminator is adopted in the first set of experiments, does this phenomenon also exist?

Finally, thank you for your insightful efforts

**Comment by K2OKOH** [comment]
As you said, it is possible that the inadequate classification ability of the existing discriminative network is the reason behind it. 
Based on Figure 3, we believe that the reason for the insufficient classification ability is that individual domain classifiers focus too much on the current significant domain information (non-significant information does not contribute much to improving domain classification accuracy). 
We believe that using a more complex classification network may improve performance, but it is not specifically aimed at discovering non-significant and non-causal features.

**Comment by zyfone** [comment]
I get it thanks~
