### ISSUE TITLE
single source domain generalization 的情况下领域分类器的领域标签怎么来的呢？

### ISSUE THREAD

**Issue by kinredon** [K2OKOH/MAD#2]
文章里面利用 domain classifier 来进行对抗学习，需要为每个领域提供领域标签（domain label），multi source 很好理解，不同的 domain 用不同的 label。但我看文章里面做的实验都是 single source 的，给出的代码里面，给同一个 domain 不同的 domain label，为什么这样设计呢？

**Comment by K2OKOH** [comment]
文章先使用SCG的方法对图像进行增强，增强后的图像认为是一个新的领域，代码中的标签是这样来的。
single source表示只使用一个数据集的图像进行领域增强。

**Comment by kinredon** [comment]
@K2OKOH 感谢你的回复！
