### ISSUE TITLE
关于论文fig.1示例的疑问

### ISSUE THREAD

**Issue by ShaneSpace** [K2OKOH/MAD#3]
作者您好，我读了您的这篇论文，收获很大。但是对于本文的Fig.1还是有点疑惑，想请您指教。
在Fig.1中，您提到在freeze特征编码器之后，在discriminitor上加了一个resblock，分类损失继续下降，以此来说明domain classifier在对抗中失效，有部分domain specific信息仍然存在。我对此有不同看法，我认为，这个是属于对抗网络中两个players的平衡问题，一般来说，生成器判别器要差不多强，才能达到理想的均衡，但是这个例子中，修改了判别器（也即增强了判别器的学习能力），自然也就不再符合之前达到的平衡。如果我上述看法是合理的话，这些残留的domain-specific information其实完全可以使用更强的doamin classifier来处理，那我是不是可以得出DANN架构中discriminitor越强越好呢

**Comment by K2OKOH** [comment]
图一展示了我们研究这个问题的切入点，从此问题上我们想到的也是领域分类器不够强（关注的内容不够丰富）。
对于这个问题，我们利用多视角领域分类器（MVDC）本质上其实是构建了一个更强的领域分类器。
但这个“更强“的侧重点不同，我们更关注领域分类器能找到更多的非因果信息，但要避免更加关注显著的那部分的特征。
当然我们觉得，或许还存在更好的方式来构建这个领域分类器，值得后续研究。

**Comment by ShaneSpace** [comment]
> 感谢回复，这么看来，增强domain classifier算是节流，而用更多view来做non-causal factor提取就算是开源吧。
