### ISSUE TITLE
MV 多视角特征输入上采样的问题

### ISSUE THREAD

**Issue by YawZhang** [K2OKOH/MAD#4]
作者您好，您的这篇论文对我启发很大。不过我有个疑问，为什么在多视角img_base_feat 要进行一步上采样得到高分辨率特征？这样做的目的是因为特征提取器的最后一层关注更多的全局语义，而多视角需要浅层网络中更多的局部信息，来进行多视角嵌入空间映射吗？

**Comment by K2OKOH** [comment]
您好，这个上采样并没有什么特殊的意义，只是对特征的大小做了个规定，并没有对特征有很大的缩放。
（其产生的原因是，我们在使用自编码器做映射前，尝试了用DCT变换来映射到频域，改成自编码器时把这一步上采样留了下来）
您可以根据需求去除这一步，并没有原理性的影响。
