### ISSUE TITLE
关于SCG的疑问

### ISSUE THREAD

**Issue by chengguanjun** [K2OKOH/MAD#5]
您好，非常感谢您开源自己的工作！但我对于SCG.py中的代码有点疑问，我不太明白23和24行代码的意思，还有论文中说使用带通滤波器将DCT频谱分为因果和非因果部分，那在代码中哪一块体现的呢？期待您的回复！

**Comment by K2OKOH** [comment]
您好，首先表示抱歉之前代码中放入的SCG是只改变图像低频部分的。
现在已经做更新，并在代码中增加了中文注释。
SCG.py这个部分是在训练前单独运行的，这个部分的代码和论文中描述的带通滤波器相比进行了一些改进，我们使用了分段函数来组成带通滤波器，可以更方便的做调整。

**Comment by chengguanjun** [comment]
@K2OKOH 好的，非常感谢！
